### ISSUE TITLE
Languages that are not in the latin alphabet don't render 

### ISSUE THREAD

**Issue by akkota** [narlock/TamoStudy#22]
![bug](https://user-images.githubusercontent.com/108426332/229469007-fdbfac98-c710-4ffc-962e-98be153a3183.png)

Prolly happening cuz Java still uses ASCII I'm guessing.  The above screen shot is with selecting the language as Japanese. Also, dutch and chinese both show english in their menus. I'm not sure if you meant to add these languages in later updates but letting you know anyways just if you happened to miss it :) 

P.S - Using windows 11

**Comment by narlock** [comment]
So this actually is an OS related issue. I don't think Windows computers come pre-installed with extended ascii / different fonts to use. Thus, it is not rendering any of the non-ascii characters. I had a discussion with @Shorent a long time ago regarding this.

Funny enough, on macOS devices, all of the languages render perfectly fine. Assuming this is because all of them come preinstalled with all language fonts or something related to that
