### ISSUE TITLE
Can't load local study profile

### ISSUE THREAD

**Issue by Akisachan** [narlock/TamoStudy#27]
I downloaded version 5.0 of tamo on windows yesterday and I created a study profile but then after I closed the programme and reopened it the local study file wasn't loaded and since then it has happened every time. The local study file is not loaded, in fact when I click on the 'local study' button no window opens, it basically doesn't do anything. Despite the fact that I have tried to click several times the button, despite the fact that I have also tried to forcibly restart the programme, despite the fact that I have uninstalled and reinstalled it several times and have also installed the latest version of java from the link the problem persists

**Comment by Akisachan** [comment]
Sure! 

1. Operating system: windows 10
2. My Java version: 1.8.0_381
3. Yes I have profile.json file in my TamoStudy folder.

**Comment by narlock** [comment]
Added this issue to todo list for analysis

**Comment by narlock** [comment]
Hi @Akisachan,

I ran the latest version of TamoStudy (v5.0.1) here (you can download it as a JAR file and run it like that instead of using the .exe): https://github.com/narlock/TamoStudy/releases/tag/b5.0

I ran this on Windows 10 using 1.8.0_371 and Windows 11 using 1.8.0_381. I did not find any way to replicate this bug. 

If you encounter this bug, please try opening either Windows Command Prompt or Powershell and running the JAR through there using `java -jar TamoStudy_Beta_v5.0.1.jar`. This should launch the application and give you logs for the app in the terminal. Upon attempting to replicate, an error should be thrown in the application.

If you stumble upon the error again, paste the stack trace into a new issue thread on here and I will look into it.

Thanks
