### ISSUE TITLE
account

### ISSUE THREAD

**Issue by adele123YI** [narlock/TamoStudy#4]
I have created my account and I can't log in

**Comment by v4virdem** [comment]
Have you tried to check the log file created in the folder? You can see if the nickname and the password are the same, maybe are write in a wrong way

**Comment by narlock** [comment]
> I have created my account and I can't log in

Hey adele123YI,

Thanks for opening an issue! I would suggest trying the following:

- Make sure you are running TamoStudy.jar in the same file folder as the assets and profile folders; This is crucial for the file input and output system to work flawlessly.
- If this is already the case, make sure that your profile exists inside of the profile folder. (You will see a text file with your username inside of it)
- Lastly, make sure upon selecting "Load Existing Profile" on the welcome screen, ensure that you are entering your username and password correctly. It IS case sensitive so even typing something with a wrong case will cause you to be unable to login.

Kindest regards,
narlock

**Comment by adele123YI** [comment]
Hey 
Thanks for your answers 
-Tamostudy.jar is in the same file as the assets and profile folders
-the profile folder is empty 
-I don't have any pictures (I've seen people having them on discord but I don't have them)

**Comment by narlock** [comment]
> Hey
> Thanks for your answers
> -Tamostudy.jar is in the same file as the assets and profile folders
> -the profile folder is empty
> -I don't have any pictures (I've seen people having them on discord but I don't have them)

Hey, thanks for the response

If you could, send a screenshot of your Finder folder with your assets, profile, and TamoStudy.jar file in them. I am curious to see if anything else could be created the issue from here.

Otherwise, I will look more into this issue. I plan to release the next release of TamoStudy sometime today, so there will be a new folder and jar file to try and run. If you can't get this version of TamoStudy to work, perhaps the next version will work.

I will continue to look for a solution if this bug persists.
Thank you :)

**Comment by adele123YI** [comment]
Hey 
Yes of course (but it's in French, sorry) 
<img width="907" alt="screenshot " src="https://user-images.githubusercontent.com/84325351/118515147-688aab00-b735-11eb-95a8-09aaf656b66e.png">

**Comment by narlock** [comment]
> Hey
> Yes of course (but it's in French, sorry)
> <img alt="screenshot " width="907" src="https://user-images.githubusercontent.com/84325351/118515147-688aab00-b735-11eb-95a8-09aaf656b66e.png">

Thank you again for sending me this image.
I will work to see if I can find a solution. I'll leave this ticket open until I can find one.

I also saw you joined our Discord server, so I may contact you there if it's easier.

**Comment by narlock** [comment]
Hey adele123YI,

I have found a temporary (and most likely the solution for now...) solution to the issue at hand.

We will solve this problem by creating a command line script. This will be similar to macOS except using the shell `sh` file extension.

To do this with Windows, follow the following steps:
- Locate your TamoStudy source folder (the folder with the assets, profiles, and TamoStudy.jar files in them)
- Copy the address of this directory. (For example, if you have this folder on your desktop, your path would look something like "C:\Users\narlock\Desktop\TamoStudy a0.5.0"
- From here, create a new text file (we will save this as a .BAT file - USE THIS EXTENSION WHEN SAVING!!) preferably store this also inside of the TamoStudy folder as well.
- From here, enter the following on both lines:
``cd C:\Users\narlock\Desktop\TamoStudy a0.5.0``
``java -jar TamoStudy.jar``
Note: Use your path (obviously) for the cd command.
- Save your file as a .BAT file
- Run the BAT file and TamoStudy will now launch with assets and read/write capabilities

From here, you will now be able to use TamoStudy. Remember, you must use the BAT file in order to launch TamoStudy every time.

I apologize that this is kind of a hassle, but I am glad that there is some solution at the moment. I will continue to look for possible fixes to this in the future that are more efficient.
